pass arguments to emacsclient

diff --git a/opt/bin/e b/opt/bin/e
--- a/opt/bin/e
+++ b/opt/bin/e
@@ -1,5 +1,27 @@
 #!/bin/sh
 
+O=()
+while test -n "$1"; do
+  case "$1" in
+   -c)
+      O=("${O[@]}" "$1")
+      shift
+      ;;
+   --)
+      shift
+      break;
+      ;;
+   -*)
+      echo "Error: unknown option $1" >&2
+      exit 1
+      ;;
+   *)
+      break;
+  esac
+done
+
+O=("${O[@]}" "-n")
+
 for ARG in "$@"; do
   FILE="${ARG%%:*}"
   FILE="$(r-findpath "$FILE")"
@@ -7,8 +29,8 @@ for ARG in "$@"; do
   LINE="${LINE#*:}"
   LINE="${LINE%%:*}"
   if [ -n "$LINE" ]; then
-      run emacsclient -n +"$LINE" "$FILE"
+      run emacsclient "${O[@]}" +"$LINE" "$FILE"
   else
-      run emacsclient -n "$FILE"
+      run emacsclient "${O[@]}" "$FILE"
   fi
 done
